apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}-transcode
  namespace: handbrk8s
spec:
  backoffLimit: 20
  template:
    metadata:
      name: {{.Name}}-transcode
    spec:
      initContainers:
      - name: prep
        image: alpine:3.5
        command: ["sh"]
        args:
        - "-xc"
        - "mkdir -p '{{.OutputDir}}'"
        volumeMounts:
        - mountPath: /work
          name: handbrk8s
      containers:
      - name: handbrake
        image: carolynvs/handbrakecli:1.2.0
        resources:
          requests:
            cpu: "3"
        args:
        - "--preset-import-file"
        - "/config/ghb/presets.json"
        - "-i"
        - "{{.InputPath}}"
        - "-o"
        - "{{.OutputPath}}"
        - "--preset"
        - "{{.Preset}}"
        volumeMounts:
        - mountPath: /work
          name: handbrk8s
        - name: handbrakecli-config
          mountPath: /config/ghb
      restartPolicy: Never
      volumes:
      - name: handbrk8s
        persistentVolumeClaim:
          claimName: handbrk8s
      - name: handbrakecli-config
        configMap:
          name: handbrakecli
