apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: handbrk8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-creator
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-reader
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: handbrk8s:job-reader
  namespace: handbrk8s
subjects:
- kind: ServiceAccount
  name: default
  namespace: handbrk8s
roleRef:
  kind: ClusterRole
  name: job-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: handbrk8s:job-creator
  namespace: handbrk8s
subjects:
- kind: ServiceAccount
  name: default
  namespace: handbrk8s
roleRef:
  kind: ClusterRole
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
