apiVersion: v1
kind: PersistentVolume
metadata:
  name: handbrk8s
  # volumes are global, and are not namespaced
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/ponyshare/handbrk8s"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: handbrk8s
  namespace: handbrk8s
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
